### ISSUE TITLE
[FRONT-BACK] - Política de contraseñas

### ISSUE THREAD

**Issue by mleonardogonzalo** [codefen/codefend-user#106]
Las contraseñas deben tener al menos 12 caracteres, una letra mayúscula, una minúscula, un número y un caracter especial.
Cantidad máxima de reintentos: 3

**Comment by chrisrusso** [comment]
Modificado en creación de usuario, invoke de usuario y cambios de password... 16 chars, 1 upper, 1 low, 1 num, 1 specialchar

**Comment by chrisrusso** [comment]
$password_regex = '/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^a-zA-Z\d\s]).{16,}$/';

Explanation of the regex:

^: Asserts the start of the string.
(?=.*[a-z]): Positive lookahead to ensure at least one lowercase letter.
(?=.*[A-Z]): Positive lookahead to ensure at least one uppercase letter.
(?=.*\d): Positive lookahead to ensure at least one digit.
(?=.*[^a-zA-Z\d\s]): Positive lookahead to ensure at least one special character. [^a-zA-Z\d\s] matches any character that is not a letter (upper or lower), digit, or whitespace.
.{16,}: Matches any character (except for line terminators) at least 16 times.
$: Asserts the end of the string.
