### ISSUE TITLE
BUG Duplicados en recursos mobile

### ISSUE THREAD

**Issue by MarcossIC** [codefen/codefend-user#112]
El BE esta permitiendo duplicar aplicaciones en los recursos mobile

![Image](https://github.com/codefen/codefend-user/assets/112729111/41ecc294-0882-47c3-93c1-1980bb54f878)

Las URL de las apps de android son algo asi: 
"https://play.google.com/store/apps/details?id=com.supercell.clashroyale&hl=es&gl=US"
En la URL hay un ID com.supercell.clashroyale, se puede verificar que si ya hay una URl con este ID no lo agregue

**Comment by chrisrusso** [comment]
No se considera un bug... es raro, o bien habría que marcar con un hash las apps*company asociadas, o conservarlo...
