### ISSUE TITLE
Sistema de notificaciones: disparar al finalizar orden

### ISSUE THREAD

**Issue by mleonardogonzalo** [codefen/codefend-user#12]
Se debe crear un sistema de notificaciones para el usuario.
Actualmente, cuando se realiza una actualización sobre un issue o cuando el usuario recibe algun tipo de respuesta, no tiene forma de saber las novedades ya que sólo se informa por mail y cuando se entra al sistema no se cuenta con información/alerta de los hechos.
En el front se debe agregar una campana en el navbar con la cual se visualizarán las notificaciones las cuales contarán con un link a la sección a la cual requiera atención.

Restan definir cuestiones visuales, de integración, etc. Esto es un borrador.

**Comment by chrisrusso** [comment]
Mecanismos de backend armado... se procede a colocar una campana.
