### ISSUE TITLE
[FRONT] - [CHECKOUT] - Unificar criterio de texto en botón continuar

### ISSUE THREAD

**Issue by mleonardogonzalo** [codefen/codefend-user#18]
En el checkout el botón continuar aparece primeramente con el text "continuar con el siguiente paso" (o similar) y luego cambia a "continue".

Se debe unificar el criterio al texto "Continuar".

**Comment by MarcossIC** [comment]
Se normalizo el criterio a "Proceed to the next step", hasta la parte del pago
