### ISSUE TITLE
[FRONT] - [TABLAS] - Cursor default cuando no hay link activo

### ISSUE THREAD

**Issue by mleonardogonzalo** [codefen/codefend-user#22]
En algunas tablas al hacer hover sobre las filas el cursor cambia a pointer lo que da a entender que la fila tiene acción/link y, como usuario, se espera alguna acción o da la sensación de que no se sabe cuando algo va a ejecutar una acción.
Como la estructura de las filas estan maquetadas con tag <a y atributo href vacío, se decide cambiar el cursor a default en acción on hover para evitar cambiar el maquetado de las tablas y dejarlas para cuando en un futuro se decida, o no, agregarle acción a esas filas. Esto solo aplica a las tablas con filas con atributo href vacío.

**Comment by MarcossIC** [comment]
Se dejo el cursor default, pero se activo el "left-marker" a las filas que no tienen acción
