### ISSUE TITLE
[FRONT-BACK] - [PREFERENCE] - La compañía debe de poder quitarle el acceso a sus recursos a un usuario

### ISSUE THREAD

**Issue by MarcossIC** [codefen/codefend-user#75]

**Comment by mleonardogonzalo** [comment]
![Image](https://github.com/codefen/codefend-user/assets/23084061/097cafca-435a-4429-adb5-e215e45252f5)

**Comment by mleonardogonzalo** [comment]
![Image](https://github.com/codefen/codefend-user/assets/23084061/2b777bcb-eea3-4fa2-a291-b3aa9665efaa)
