### ISSUE TITLE
[BACK] - [NUEVO-USUARIO] - IDs remanentes de otras cuentas

### ISSUE THREAD

**Issue by mleonardogonzalo** [codefen/codefend-user#78]
Al crear un nuevo usuario aparecen recursos “remanentes” de otras cuentas (Fallo con los ID en base de datos)

![Image](https://github.com/codefen/codefend-user/assets/23084061/4c8e88bc-a6e8-406f-9e4f-05ea870b78d3)

**Comment by chrisrusso** [comment]
No se observan más records de id elevado (generando el problema) en la base. No debería de pasar más.

**Comment by chrisrusso** [comment]
Probar y archivar!

**Comment by chrisrusso** [comment]
Probar con 10 empresas nuevas.
