### ISSUE TITLE
[BACK] - [WEB] - Timeout al agregar recurso

### ISSUE THREAD

**Issue by mleonardogonzalo** [codefen/codefend-user#80]
La API al tardar más de 12 seg, el frontend cancela la request dando este error. A pesar del mensaje de error debido al “timeout”, el recurso se agrega correctamente y aparece al entrar y salir de la página.

**Comment by chrisrusso** [comment]
Esto no es un problema o algo que pueda ser abordado desde el backend. El sistema manda pedidos a diversas APIs para sacar los subdominios, debería de considerarse un timeout más alto para correr esta función.
