### ISSUE TITLE
[BACK] - [CLOUD] - Error de permisos al solicitar recursos

### ISSUE THREAD

**Issue by mleonardogonzalo** [codefen/codefend-user#90]
Fallo al solicitar recursos CLOUD como proveedor, cuenta con acceso a la compañía 124, pero al solicitar recursos CLOUD, devuelve que no tiene permisos (Solo ocurre en CLOUD)

![Image](https://github.com/codefen/codefend-user/assets/23084061/70900c17-04bd-4444-8cdb-79e40b5dfb1b)

![Image](https://github.com/codefen/codefend-user/assets/23084061/cf251590-1be5-4768-8d62-143c8fedf4f4)

![Image](https://github.com/codefen/codefend-user/assets/23084061/5c13cae8-3d17-4800-81cd-0d35243a3c6c)

**Comment by chrisrusso** [comment]
Rarisimo... no se mira mucho cloud. Lo subo en orden de prioridad.
