### ISSUE TITLE
[BACK] - [NEW-ISSUE-CS] - Mail con datos vacíos

### ISSUE THREAD

**Issue by mleonardogonzalo** [codefen/codefend-user#91]
El email que recibe el cliente al recibir un mensaje en una issue es:

![Image](https://github.com/codefen/codefend-user/assets/23084061/d1c7acba-58d6-45aa-aef3-28fe681cb186)

**Comment by chrisrusso** [comment]
Este issue no se debe a una vulnerabilidad sin información, sino al hecho de que envía el mismo mail para el issues_cs, en cuyo caso no concuerda la información.
