### ISSUE TITLE
[BACK] - [PENTEST] - Error cuando la empresa del solicitante y proveedor es el mismo

### ISSUE THREAD

**Issue by mleonardogonzalo** [codefen/codefend-user#97]
Si un usuario de una compañía solicita un pentest y lo acepta un proveedor que es de la misma compañía (En este ejemplo “codefend” solicitó un pentest y los proveedores que aceptaron también son de “codefend”). Ocurre lo siguiente, el back devuelve los miembros duplicados, debido a que separa los miembros de la compañía de los proveedores, y el usuario al clasificar como ambos duplica resultado.
Como extra, los usuarios proveedores deberían de aparecer por default en esta tabla? En caso que se les quita acceso desaparecen de la tabla? O simplemente desactivar el icono? Dejar de tener acceso es equivalente a no ser parte de la compañía? Un usuario proveedor debería ser parte de una compañía si no tiene acceso a esta?

![Image](https://github.com/codefen/codefend-user/assets/23084061/10decbad-fd73-4aca-80dc-d32f7d4bc3d6)

**Comment by chrisrusso** [comment]
Este problema estaba vinculado a un error en la query que seleccionaba los usuarios invitados a una compañía, ya fue corregido. Las empresas como Codefend donde hay hackers adentro pidiendo un pentest a ser realizados por uno de sus miembros, no son normales en el sistema. No se requiere modificación inmediata.
